/**
* This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
*
* Do not edit this file as changes may cause incorrect behavior and will be lost
* once the code is regenerated.
*
* @generated by codegen project: GeneratePropsJavaInterface.js
*/

package com.facebook.react.viewmanagers;

import android.view.View;
import androidx.annotation.Nullable;
import com.facebook.react.bridge.ReadableArray;
import com.facebook.react.bridge.ReadableMap;

public interface RNMapsHeatmapManagerInterface<T extends View> {
  void setGradient(T view, @Nullable ReadableMap value);
  void setOpacity(T view, double value);
  void setPoints(T view, @Nullable ReadableArray value);
  void setRadius(T view, double value);
}
